### ISSUE TITLE
请问弹出黑框是哪段代码，想知道是否能优化消去

### ISSUE THREAD

**Issue by wolfdan666** [LuffyLSX/auto-arknights#8]
大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情

**Comment by LuffyLSX** [comment]
链接：https://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g 
提取码：oje4 
github上传不了压缩包，解压后安装好adb就可以使用了，目前来说偶尔模拟器会卡死重启即可

**Comment by LuffyLSX** [comment]
> 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情

链接：https
://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可

**Comment by wolfdan666** [comment]
> > 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情
> 
> 链接：https
> ://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
> github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可

大佬大佬，你这个有源码吗？gui开始完全懵逼

**Comment by LuffyLSX** [comment]
> > > 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情
> > 
> > 
> > 链接：https
> > ://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
> > github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可
> 
> 大佬大佬，你这个有源码吗？gui开始完全懵逼

有的，就在gui分支里，使用的是pyqt5模块

**Comment by wolfdan666** [comment]
> > > > 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情
> > > 
> > > 
> > > 链接：https
> > > ://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
> > > github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可
> > 
> > 
> > 大佬大佬，你这个有源码吗？gui开始完全懵逼
> 
> 有的，就在gui分支里，使用的是pyqt5模块

emmmm，压缩包里都找过了，没有gui分支，还有我刚刚试了下，gui这个版本连不上模拟器，难道是因为我电脑分辨率是1080P的原因吗

**Comment by wolfdan666** [comment]
> > > > 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情
> > > 
> > > 
> > > 链接：https
> > > ://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
> > > github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可
> > 
> > 
> > 大佬大佬，你这个有源码吗？gui开始完全懵逼
> 
> 有的，就在gui分支里，使用的是pyqt5模块

又试了几次，又可以用了，尴尬

**Comment by LuffyLSX** [comment]
> > > > > 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情
> > > > 
> > > > 
> > > > 链接：https
> > > > ://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
> > > > github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可
> > > 
> > > 
> > > 大佬大佬，你这个有源码吗？gui开始完全懵逼
> > 
> > 
> > 有的，就在gui分支里，使用的是pyqt5模块
> 
> emmmm，压缩包里都找过了，没有gui分支，还有我刚刚试了下，gui这个版本连不上模拟器，难道是因为我电脑分辨率是1080P的原因吗

gui分支是在GitHub上面，如果有问题的话可以b站私信我，这里讨论太难受了，id：玩游戏的陆飞

**Comment by wolfdan666** [comment]
> > > > > > 大佬，请问弹出黑框是哪段代码，想知道是否能优化消去，因为我想后台运行刷脚本，然后做其他事情
> > > > > 
> > > > > 
> > > > > 链接：https
> > > > > ://pan.baidu.com/s/1mW8m0TgLD6CRa7vdVVRg4g提取代码：oje4
> > > > > github上传不了压缩包，解压后安装好adb就可以使用了，目前而言偶尔模拟器会卡死重启即可
> > > > 
> > > > 
> > > > 大佬大佬，你这个有源码吗？gui开始完全懵逼
> > > 
> > > 
> > > 有的，就在gui分支里，使用的是pyqt5模块
> > 
> > 
> > emmmm，压缩包里都找过了，没有gui分支，还有我刚刚试了下，gui这个版本连不上模拟器，难道是因为我电脑分辨率是1080P的原因吗
> 
> gui分支是在GitHub上面，如果有问题的话可以b站私信我，这里讨论太难受了，id：玩游戏的陆飞

感谢大佬，这样子模拟手点应该不会被封号，哈哈哈，劳动人民的智慧
